
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Samples.UI {
    using System;
    using Terminal.Gui;
    
    
    public partial class ChatWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.FrameView chatFrameView;
        
        private Terminal.Gui.TextView chatTextView;
        
        private Terminal.Gui.FrameView userListFrame;
        
        private Terminal.Gui.ListView userListView;
        
        private Terminal.Gui.FrameView messageFrameView;
        
        private Terminal.Gui.TextField textMessageField;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.FrameView frameLogMessages;
        
        private Terminal.Gui.TextView logsTextView;
        
        private void InitializeComponent() {
            this.logsTextView = new Terminal.Gui.TextView();
            this.frameLogMessages = new Terminal.Gui.FrameView();
            this.button = new Terminal.Gui.Button();
            this.textMessageField = new Terminal.Gui.TextField();
            this.messageFrameView = new Terminal.Gui.FrameView();
            this.userListView = new Terminal.Gui.ListView();
            this.userListFrame = new Terminal.Gui.FrameView();
            this.chatTextView = new Terminal.Gui.TextView();
            this.chatFrameView = new Terminal.Gui.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.chatFrameView.Width = Dim.Fill() - 20;
            this.chatFrameView.Height = Dim.Fill() - 8;
            this.chatFrameView.X = 0;
            this.chatFrameView.Y = 0;
            this.chatFrameView.Visible = true;
            this.chatFrameView.Data = "frameView";
            this.chatFrameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.chatFrameView.Border.Effect3D = false;
            this.chatFrameView.Border.Effect3DBrush = null;
            this.chatFrameView.Border.DrawMarginFrame = true;
            this.chatFrameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chatFrameView.Title = "Chat";
            this.Add(this.chatFrameView);
            this.chatTextView.Width = Dim.Fill(0);
            this.chatTextView.Height = Dim.Fill(0) - 3;
            this.chatTextView.X = 0;
            this.chatTextView.Y = 0;
            this.chatTextView.Visible = true;
            this.chatTextView.Data = "chatListView";
            this.chatTextView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.chatTextView.Text = "";
            this.chatTextView.ReadOnly = true;
            this.chatFrameView.Add(this.chatTextView);
            this.userListFrame.Width = 20;
            this.userListFrame.Height = Dim.Fill() - 8;
            this.userListFrame.X = Pos.Right(chatFrameView);
            this.userListFrame.Y = 0;
            this.userListFrame.Visible = true;
            this.userListFrame.Data = "userListFrame";
            this.userListFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.userListFrame.Border.Effect3D = false;
            this.userListFrame.Border.Effect3DBrush = null;
            this.userListFrame.Border.DrawMarginFrame = true;
            this.userListFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.userListFrame.Title = "Peers";
            this.Add(this.userListFrame);
            this.userListView.Width = Dim.Fill();
            this.userListView.Height = Dim.Fill() - 8;
            this.userListView.X = 0;
            this.userListView.Y = 0;
            this.userListView.Visible = true;
            this.userListView.Data = "userListView";
            this.userListView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.userListView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.userListView.AllowsMarking = false;
            this.userListView.AllowsMultipleSelection = true;
            this.userListFrame.Add(this.userListView);
            this.messageFrameView.Width = Dim.Fill(0);
            this.messageFrameView.Height = 3;
            this.messageFrameView.X = 0;
            this.messageFrameView.Y = Pos.Bottom(chatTextView);
            this.messageFrameView.Visible = true;
            this.messageFrameView.Data = "messageFrameView";
            this.messageFrameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.messageFrameView.Border.Effect3D = false;
            this.messageFrameView.Border.Effect3DBrush = null;
            this.messageFrameView.Border.DrawMarginFrame = true;
            this.messageFrameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.messageFrameView.Title = "Type message";
            this.chatFrameView.Add(this.messageFrameView);
            this.textMessageField.Width = Dim.Fill() - 12;
            this.textMessageField.Height = Dim.Fill();
            this.textMessageField.X = 0;
            this.textMessageField.Y = 0;
            this.textMessageField.Visible = true;
            this.textMessageField.Secret = false;
            this.textMessageField.Data = "textMessageField";
            this.textMessageField.Text = "";
            this.textMessageField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.messageFrameView.Add(this.textMessageField);
            this.button.Width = 12;
            this.button.Height = 1;
            this.button.X = Pos.Right(textMessageField);
            this.button.Y = 0;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "Send";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.messageFrameView.Add(this.button);
            this.frameLogMessages.Width = Dim.Fill();
            this.frameLogMessages.Height = 8;
            this.frameLogMessages.X = 0;
            this.frameLogMessages.Y = Pos.Bottom(chatFrameView);
            this.frameLogMessages.Visible = true;
            this.frameLogMessages.Data = "frameView5";
            this.frameLogMessages.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameLogMessages.Border.Effect3D = false;
            this.frameLogMessages.Border.Effect3DBrush = null;
            this.frameLogMessages.Border.DrawMarginFrame = true;
            this.frameLogMessages.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameLogMessages.Title = "Logs";
            this.Add(this.frameLogMessages);
            this.logsTextView.Width = Dim.Fill(0);
            this.logsTextView.Height = Dim.Fill(0);
            this.logsTextView.X = 0;
            this.logsTextView.Y = 0;
            this.logsTextView.Visible = true;
            this.logsTextView.Data = "listLogMessages";
            this.logsTextView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.logsTextView.Text = "";
            this.logsTextView.ReadOnly = true;
            this.frameLogMessages.Add(this.logsTextView);
        }
    }
}
